import './globals.css'
import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import {Nav} from "@/app/componets/Nav";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">

        <body
        style={{  }}
            className=" bg-gradient-to-br from-gray-700 via-gray-900 to-black">
        <Nav/>
        {
            children}
        </body>
        </html>
    )
}
